version: "3"

services:
  web:
    container_name: calendar
    build: .
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: calendar-mysql
      MYSQL_PASSWORD: insecurepassword
    networks:
      - calendar_network
    volumes:
      - .:/calendar
    tty: true
    stdin_open: true
    command: sh -c 'rm -f tmp/pids/server.pid && bundle install -j4 && bundle exec rails server -b 0.0.0.0 -p 3000'
  db:
    image: mysql:5.7
    container_name: calendar-mysql
    environment:
      MYSQL_ROOT_PASSWORD: insecurepassword
    networks:
      - calendar_network
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
networks:
  calendar_network:
    external: true
