version: "3"

services:
  web:
    container_name: calender
    build: .
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: calender-mysql
      MYSQL_PASSWORD: insecurepassword
    networks:
      - calender_network
    volumes:
      - .:/calender
    tty: true
    stdin_open: true
    command: sh -c 'bundle install -j4 && bundle exec rails server -b 0.0.0.0 -p 3000'
  db:
    image: mysql:5.7
    container_name: calender-mysql
    environment:
      MYSQL_ROOT_PASSWORD: insecurepassword
    networks:
      - calender_network
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
networks:
  calender_network:
    external: true
